# numpy

[absolute_beginners](https://numpy.org/doc/1.26/user/absolute_beginners.html)

## NumPy 基础概念

- Ndarray：理解 N 维数组，特别是 shape (维度) 的概念。

- 广播机制 (Broadcasting)：这是 NumPy 最强大的特性，允许不同维度的数组进行数学运算。

- 向量化计算：学会用数组操作代替 Python 的 for 循环（速度快几十倍）。

## narray

In [5]:
import numpy as np

a = np.array([[1,2], [2, 3]])
print(a.shape)
a.dtype

(2, 2)


dtype('int32')

## array creation

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

## Broadcasting

In [20]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
a + b 

array([11, 22, 33])

## Universal Functions

In [21]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
# e^x = y
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
np.maximum(a, 2)

array([2, 2, 3])

## Aggregations

In [27]:
a.sum()

6

In [30]:
a.mean(axis=0)

2.0

In [32]:
a.max(axis=0)

3

## Shape Manipulation

In [34]:
a.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [35]:
a.T

array([1, 2, 3])

In [36]:
np.concatenate([a, a], axis=0)

array([1, 2, 3, 1, 2, 3])

In [37]:
np.stack((a, a), axis=0)

array([[1, 2, 3],
       [1, 2, 3]])

## Linear Algebra

$$
A = 
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

$$
det(A) = ad-bc
$$

In [ ]:
A = np.array([[1, 2], [3, 4]])
# 1*4 - 2*3 = -2
np.linalg.det(A)

-2.0000000000000004

$$
A = 
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

$$
inv(A) = A^{-1} = \frac{1}{ad - bc}
\begin{bmatrix}
d & -b \\
-c & a
\end{bmatrix}

$$

In [40]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

$$
A = 
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

$$
A \cdot A = 
\begin{bmatrix}
a^2 + bc & ab + bd \\
ca + dc & cb + d^2
\end{bmatrix}
$$

In [41]:
np.dot(A, A)

array([[ 7, 10],
       [15, 22]])

## Radom Module

In [42]:
rng = np.random.default_rng(42)
rng.integers(0, 10, size=5)

array([0, 7, 6, 4, 4], dtype=int64)

In [43]:
rng.normal(0, 1, size=(2, 2))

array([[ 0.94056472, -1.95103519],
       [-1.30217951,  0.1278404 ]])