# transformers

In [7]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-base-chinese', use_fast=True)

sentences = ["我觉得不行", "我觉得其实还可以"]

batch_inputs = tokenizer(
    sentences,
    padding=True,
    return_tensors="pt"
)

print(batch_inputs["input_ids"], "\n", type(batch_inputs["input_ids"]))
print(batch_inputs["input_ids"].shape)

batch_inputs

tensor([[ 101, 2769, 6230, 2533,  679, 6121,  102,    0,    0,    0],
        [ 101, 2769, 6230, 2533, 1071, 2141, 6820, 1377,  809,  102]]) 
 <class 'torch.Tensor'>
torch.Size([2, 10])


{'input_ids': tensor([[ 101, 2769, 6230, 2533,  679, 6121,  102,    0,    0,    0],
        [ 101, 2769, 6230, 2533, 1071, 2141, 6820, 1377,  809,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [8]:
# slow tokenizer才有 Encoding
print(batch_inputs[0], "\n", type(batch_inputs[0]))

# torch.Tensor


Encoding(num_tokens=10, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing]) 
 <class 'tokenizers.Encoding'>


| 写法                          | 实际含义                           |
| --------------------------- | ------------------------------ |
| `batch_inputs["input_ids"]` | 从 `data` 里取模型输入                |
| `batch_inputs[i]`           | 从 `encodings` 里取第 i 个 Encoding |


## Model Forward

In [9]:
from transformers import AutoModel

model = AutoModel.from_pretrained("bert-base-chinese")


In [10]:
import torch

with torch.no_grad():
    # **batch_inputs 字典解包
    outputs = model(**batch_inputs)

print(f"输出对象的类型: {type(outputs)}")
# 核心产出：last_hidden_state (最后一层的隐藏状态)
print(f"向量形状: {outputs.last_hidden_state.shape}")

输出对象的类型: <class 'transformers.modeling_outputs.BaseModelOutputWithPoolingAndCrossAttentions'>
向量形状: torch.Size([2, 10, 768])


In [11]:
# 提示：取出第 0 个位置的 token 向量
cls_embeddings = outputs.last_hidden_state[:, 0, :] 
print(cls_embeddings.shape) # 应该是 [2, 768]

torch.Size([2, 768])


In [12]:
from transformers import AutoModel

model = AutoModel.from_pretrained("bert-base-chinese")

# for name, param in model.named_parameters():
#     print(name, param.requires_grad)


In [13]:
inputs = {
    "input_ids": torch.tensor([[101, 2769, 6230, 2533, 679, 6121, 102]]),
    "attention_mask": torch.tensor([[1, 1, 1, 1, 1, 1, 1]])
}

outputs = model(**inputs)
loss = outputs.last_hidden_state.sum()
loss.backward()

print(model.embeddings.word_embeddings.weight.grad is None)


False


# print cuda infos

In [1]:
import torch


def bytes_to_gb(x: int) -> float:
    return round(x / 1024 / 1024 / 1024, 2)


def check_cuda_info():
    print("===== CUDA / GPU 信息检测 =====")

    # 1. CUDA 是否可用
    cuda_available = torch.cuda.is_available()
    print(f"CUDA Available: {cuda_available}")

    if not cuda_available:
        print("当前环境未检测到可用 CUDA")
        return

    # 2. CUDA 版本
    print(f"CUDA Version (PyTorch built): {torch.version.cuda}")

    # 3. GPU 数量
    device_count = torch.cuda.device_count()
    print(f"GPU Count: {device_count}")

    for device_id in range(device_count):
        props = torch.cuda.get_device_properties(device_id)

        total_mem = props.total_memory
        allocated = torch.cuda.memory_allocated(device_id)
        reserved = torch.cuda.memory_reserved(device_id)
        free_mem = total_mem - reserved

        print(f"\n--- GPU {device_id} ---")
        print(f"Name              : {props.name}")
        print(f"Total Memory (GB) : {bytes_to_gb(total_mem)}")
        print(f"Allocated (GB)    : {bytes_to_gb(allocated)}")
        print(f"Reserved (GB)     : {bytes_to_gb(reserved)}")
        print(f"Free (GB)         : {bytes_to_gb(free_mem)}")


if __name__ == "__main__":
    check_cuda_info()


===== CUDA / GPU 信息检测 =====
CUDA Available: False
当前环境未检测到可用 CUDA


run in google Colab

```text
===== CUDA / GPU 信息检测 =====
CUDA Available: True
CUDA Version (PyTorch built): 12.6
GPU Count: 1

--- GPU 0 ---
Name              : Tesla T4
Total Memory (GB) : 14.74
Allocated (GB)    : 0.0
Reserved (GB)     : 0.0
Free (GB)         : 14.74
```

# cases

## Tokenization & embeddings

In [1]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
out = tokenizer("Transformers are powerful", return_tensors="pt")

print(out["input_ids"])
print(out["attention_mask"])

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

d:\software\anaconda3\envs\ai-env\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\jackc\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tensor([[  101, 19081,  2024,  3928,   102]])
tensor([[1, 1, 1, 1, 1]])


## Text classification

In [2]:
from transformers import pipeline

clf = pipeline("text-classification", model="distilbert-base-uncased-finetuned-sst-2-english")
clf("This product is amazing")


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

d:\software\anaconda3\envs\ai-env\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\jackc\.cache\huggingface\hub\models--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

Device set to use cpu


[{'label': 'POSITIVE', 'score': 0.9998852014541626}]

In [12]:
clf("This product is suck")

[{'label': 'NEGATIVE', 'score': 0.9997743964195251}]

## Token classification (NER)

In [13]:

ner = pipeline("ner", model="dslim/bert-base-NER")
ner("John works at Microsoft in Seattle")


config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

d:\software\anaconda3\envs\ai-env\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\jackc\.cache\huggingface\hub\models--dslim--bert-base-NER. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP downl

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

Some weights of the model checkpoint at dslim/bert-base-NER were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cpu


[{'entity': 'B-PER',
  'score': 0.99903893,
  'index': 1,
  'word': 'John',
  'start': 0,
  'end': 4},
 {'entity': 'B-ORG',
  'score': 0.9988908,
  'index': 4,
  'word': 'Microsoft',
  'start': 14,
  'end': 23},
 {'entity': 'B-LOC',
  'score': 0.99898297,
  'index': 6,
  'word': 'Seattle',
  'start': 27,
  'end': 34}]

## Text generation

In [ ]:
from transformers import pipeline

# gen = pipeline("text-generation", model="gpt2")
# gen("Explain transformers in simple terms", max_new_tokens=50)


## run model locally with transformers

In [14]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, TextStreamer

# 修改这一行
model_path = "D:/ollama/Phi_3_5_mini_instruct"
# 2. 加载 Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=False)

# 3. 加载模型 (关键修改)
print("正在加载模型 (使用磁盘卸载技术以防崩溃)...")
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    # 🔴 改回 float16 以节省一半内存 (虽然 CPU 跑 float16 慢，但 float32 你内存不够)
    dtype=torch.float16, 
    
    # 🔴 自动分配设备，内存不够就放硬盘
    device_map="auto",
    
    # 🔴 指定卸载文件夹 (必须有这个才能利用硬盘当内存)
    offload_folder="offload_weights", 
    
    trust_remote_code=False,
    attn_implementation="eager"
)

# 4. 准备流式输出
streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

# 5. 准备输入
prompt = "write a python code call model with transformers?"
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

# 6. 生成
print("开始生成 (CPU + 硬盘模式，速度会较慢，请耐心等待):")
outputs = model.generate(
    **inputs, 
    max_new_tokens=100, 
    streamer=streamer
)

`torch_dtype` is deprecated! Use `dtype` instead!


正在加载模型 (使用磁盘卸载技术以防崩溃)...


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Some parameters are on the meta device because they were offloaded to the cpu and disk.


开始生成 (CPU + 硬盘模式，速度会较慢，请耐心等待):


# Answer
To call a model using the Transformers library in Python, you'll need to follow these steps:

1. Install the Transformers library if you haven't already:

```bash
pip install transformers
```

2. Import the necessary modules:

```python
from transformers import AutoTokenizer, AutoModelForSequenceClassification
```

3. Load the tokenizer and model for the 

KeyboardInterrupt: 